name: Test Secret Value

on:
  push:

jobs:
  test-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          DEBUG_TEST_KEY: ${{ secrets.TEST_KEY }}
          DEBUG_TEST_KEY2: ${{ secrets.TEST_KEY2 }}
        run: |
          echo $DEBUG_TEST_KEY >> secrets.txt
          echo $DEBUG_TEST_KEY2 >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
