name: Test Secret Value

on:
  push:

jobs:
  test-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set Secret as Environment Variable
        run: echo "TEST_KEY=${{ secrets.TEST_KEY2 }}"
