name: Test Secret Value

on:
  push:

jobs:
  test-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        run: |
          echo DEBUG_TEST_KEY: ${{ secrets.TEST_KEY }} | sed 's/./& /g'
          echo DEBUG_TEST_KEY2: ${{ secrets.TEST_KEY2 }} | sed 's/./& /g'
