name: Test Secret Value

on:
  push:
    branches:
      - main

jobs:
  test-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set Secret as Environment Variable
        run: echo "TEST_KEY=${{ secrets.TEST_KEY }}" >> $GITHUB_ENV

      - name: Display Secret Value
        run: |
          echo "Secret Value: $TEST_KEY"
